"""empty message

Revision ID: 1342717cfb0b
Revises: 8251fc0705bb
Create Date: 2021-05-01 22:10:36.688563

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1342717cfb0b'
down_revision = '8251fc0705bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('tags', sa.String(length=4096), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('items', 'tags')
    # ### end Alembic commands ###
