"""empty message

Revision ID: 236ed1191a97
Revises: c66378fbda1a
Create Date: 2021-04-18 20:29:26.456894

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '236ed1191a97'
down_revision = 'c66378fbda1a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('rating', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comments', 'rating')
    # ### end Alembic commands ###
