"""empty message

Revision ID: 8251fc0705bb
Revises: 236ed1191a97
Create Date: 2021-04-27 02:38:07.276616

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8251fc0705bb'
down_revision = '236ed1191a97'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('image', sa.String(length=4096), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('items', 'image')
    # ### end Alembic commands ###
